[package]
name = "nthasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md4 = "0.9"
#pprof = { version = "0.6.1", features = ["flamegraph"] }

#[profile.release]
#debug = true
